trigger:
- azure-pipelines
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: djbinghamRegistry
- script: ls -la && git status
- task: Docker@2
  displayName: Build and Push
  inputs:
    command: buildAndPush
