trigger:
- azure-pipelines
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Build and Push
  inputs:
    containerRegistry: 'mcCntRegistry Connection'
    repository: 'elm-lmp-web'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'