trigger:
  batch: true
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureContainerRegistry: djbinghamRegistry
  azureSubscriptionEndpoint: djbinghamResourceManager
  system.debug: true

steps:
- task: Bash@3
  inputs:
    script: sudo docker-compose build

- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 18.09.2-ce
    releaseType: stable

- task: DockerCompose@0
  displayName: Build services
  inputs:
    action: Build services
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerComposeFile: docker-compose.yml
    additionalDockerComposeFiles: docker/compose.test.yml
    projectName: $(Build.Repository.Name)
    qualifyImageNames: true
    additionalImageTags: $(Build.BuildId)

- task: DockerCompose@0
  displayName: Run unit tests
  inputs:
    action: Run a specific service
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerComposeFile: docker/compose.test.yml
    projectName: $(Build.Repository.Name)
    qualifyImageNames: true
    serviceName: unit-test
    detached: false

- task: DockerCompose@0
  displayName: Push services
  inputs:
    action: Push services
    azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
    azureContainerRegistry: $(azureContainerRegistry)
    dockerComposeFile: docker-compose.yml
    projectName: $(Build.Repository.Name)
    qualifyImageNames: true
    additionalImageTags: $(Build.BuildId)
